<?php
/**
 * @file
 * Adds a "description" tab to objects.
 */

/**
 * Implements hook_menu().
 */
function islandora_simple_description_menu() {
  $items = array();
  $items['islandora/object/%islandora_object/description'] = array(
    'title' => 'Description',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'islandora_simple_description_description_display',
    'page arguments' => array(2),
    'access callback' => 'islandora_simple_description_description_access',
  );
  $items['admin/islandora/simple_description'] = array(
    'title' => 'Simple Description',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_simple_description_admin_form'),
    'access arguments' => array('edit fedora metadata'),
    'file' => 'includes/admin.form.inc',
  );
  return $items;
}

/**
 * Access callback for simple description.
 */
function islandora_simple_description_description_access() {
  if (user_access('view fedora repository objects')) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Renders the description display.
 */
function islandora_simple_description_description_display($object) {
  // Load the variables we need.
  $dsid = variable_get('islandora_simple_description_dsid', 'DC');
  $query = variable_get('islandora_simple_description_xpath', '//dc:description');
  // Create a form array.
  $output = array();
  // Create the fieldset title for the array.
  $output['title'] = array(
    '#type' => 'fieldset',
    '#title' => t('Description'),
    '#collapsible' => FALSE,
  );
  // Load the object we want.
  $object = islandora_object_load($object);
  // Check if the object has the specified datastream.
  if (isset($object[$dsid])) {
    // If it does, load the datastream as XML.
    $mods = simplexml_load_string($object[$dsid]->content);
    // Do the Xpath query for the abstract.
    $abstract = $mods->xpath($query);
    // If we find something, stick it in the title fieldset as markup. If we
    // don't, just display a message saying it wasn't there.
    $output['title']['description'] = array(
      '#markup' => isset($abstract[0]) ? (string) $abstract[0] : "No $dsid description metadata found for this object.",
    );
  }
  // If there is no specified datastream, put that in the description instead.
  else {
    $output['title']['description'] = array(
      '#markup' => "No $dsid metadata was found for this object.",
    );
  }
  // Finally, return the form array to hook_menu.
  return $output;
}